[api_credentials]
openai_api_key = ""
firebase_api_key = ""
google_api_key= ""

[project]
openai_api_key=""

[aws]
aws_access_key_id = "neo4j"
aws_secret_access_key = ""
aws_session_token = ""
aws_region_name = "us-west-2"

[github]
github_token = ""

[gitlab]
gitlab_token = ""

